name: c_hello_world_ffi
version: 0.0.1
description: >-
  Simple example of calling C code from Dart with FFI

# This example isn't intended for publishing on pub.dev.
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies: 
  path: ^1.8.0


